### PR TITLE
Reduce changes between QString <-> QByteArray

### PR DESCRIPTION
**Pull request by aleixpol**
Make sure we explicitly call constructors

### CODE REVIEW

**Comment by dantti** [comment]
I'm confused a bit by some parts of this patch, especially the conversion of connectNotify, first because it was an overwrite so you could not change the type, second because since we dropped Qt4 support we can actually remove the char * implementation completely, then the QList of connected stuff should maybe use QMetaMethod?

**Comment by aleixpol** [comment]
This change uses QMetaMethod as you recommended. even better. :)

**Comment by dantti** [comment]
Awesome :) do you know if it's fine to use override keyword? I normally use Q_DECL_OVERRIDE.

please merge :D

**Comment by aleixpol** [comment]
It's fine, especially assuming we support gcc and clang.

**Pull request merged**
