### PR TITLE
Implement offlineTrigger

### PR DESCRIPTION
**Pull request by aleixpol**
It was never added to the Qt bindings

### CODE REVIEW

**Comment by dantti** [comment]
I think it would be interesting to also have an async version, which iirc was the case of the other methods.

**Comment by aleixpol** [comment]
What do you mean? It's async there.

Do you want it to return the QDBusReply? or an object wrapping it?

**Comment by dantti** [comment]
It's a blocking call, you need to return QDBusPendingReply to not block.

**Comment by aleixpol** [comment]
No, you don't need to return anything in fact. We can return it so the user can track the result of the call if you feel it's important.

**Comment by dantti** [comment]
An option would be to have a signal for trigger failed, but still you need to replace the QDBusReply with the pending one or it will block till PK has replied. Which is why returning a QDBusPendingReply object as I already did for other methods will avoid such need.

**Comment by aleixpol** [comment]
Ping?

**Comment by dantti** [comment]
sorry didn't see your update

**Pull request merged**
