### PR TITLE
Fix pkg-config

### PR DESCRIPTION
**Pull request by pvuorela**
Not sure if that header moving was a good thing, now header placement is inconsistent with e.g. PackageKit-glib2 that uses /usr/include/PackageKit/packagekit-glib2. 

Seemed like idea was that code would change #include <Transaction> to #include <PackageKit/Transaction> but leaving PackageKit out from end of -I doesn't work either, header tries to do #include <packagekitqt_global.h> which fails in that case.

Anyway, now pkg-config should work again.

### CODE REVIEW

**Comment by dantti** [comment]
Isn't it still possible to use some @MACRO@ for paths?

**Comment by pvuorela** [comment]
> Isn't it still possible to use some @macro@ for paths?

Not following. What do you mean?

**Comment by dantti** [comment]
CMake has a bunch of useful variables I'm not sure if one would be suitable to keep -l@LIBNAME@ of some other cmake macro. Just so this file is less touched in future.

**Comment by aleixpol** [comment]
Sorry, I don't see how this patch fixes or changes anything.

**Comment by pvuorela** [comment]
> Sorry, I don't see how this patch fixes or changes anything.

```Libs: -L${libdir} -l@LIBNAME@```
commit 58e4512f47c43c336fcbfcf4be3f removed LIBNAME and hardcoded packagekitqt5 to other places. After that above line resolved to "Libs: -L${libdir} -l " which doesn't help much linking.

```Cflags: -I${includedir}/PackageKit/@LIBNAME@```
After LIBNAME fix, that would resolve to Cflags: -I${includedir}/PackageKit/packagekitqt5 and further /usr/include/PackageKit/packagekitqt5 which doesn't anymore contain anything. Should be /usr/include/packagekitq5/PackageKit like you changed the installation with commit 7248b030c0885

**Comment by aleixpol** [comment]
You are very right, sorry. Just forgot about the pc files.

**Pull request merged**
