### PR TITLE
Properly expose enums for introspection

### PR DESCRIPTION
**Pull request by aleixpol**
See https://woboq.com/blog/q_enum.html

### CODE REVIEW

**Comment by dantti** [comment]
Doesn't this breaks ABI? If not do not forget to raise Qt requirement to 5.5 iirc

**Comment by aleixpol** [comment]
True about the Qt 5.5 dep.
I don't think it breaks ABI. It adds things, doesn't remove, and it doesn't have anything to do with virtuals.

**Comment by dantti** [comment]
Well it remove the old Q_ENUMS style but I guess that is also only used in the implementation moc so probably no big deal

**Comment by aleixpol** [comment]
Yes, moc will process the Q_ENUM just the same.

**Pull request merged**
