### PR TITLE
Prefer invoking methods by pointer rather than by name

### PR DESCRIPTION
**Pull request by aleixpol**
It's faster as it's resolved at compile-time.

### CODE REVIEW

**Comment by dantti** [comment]
nice thanks, but maybe we need an ifdef since this is new since 5.10?

**Comment by aleixpol** [comment]
> nice thanks, but maybe we need an ifdef since this is new since 5.10?

Really? 5.10 has been unsupported for years. Even 5.12 which was the latest LTS.
Shouldn't I just bump the minimum API?

**Comment by dantti** [comment]
well I got used to not bump Qt version for Cutelyst, I guess we just need to make sure 5.10 is required then :)

**Comment by ximion** [comment]
I agree, I think we can absolutely require Qt 5.10 - that's even backport-safe to LTS distributions :-)

**Review by ximion — APPROVED** [review]

**Comment by ximion** [comment]
Can you bump the Qt version requirement in https://github.com/hughsie/PackageKit-Qt/blob/master/src/CMakeLists.txt as well with this patch?

**Comment by aleixpol** [comment]
Done

**Pull request merged**
