### PR TITLE
Next version includes new API, so we need a minor version bump

### PR DESCRIPTION
**Pull request by aleixpol**

### CODE REVIEW

**Comment by dantti** [comment]
We are missing version tags too.

**Comment by aleixpol** [comment]
you mean git tags?

**Comment by dantti** [comment]
yeah, not sure it's my fault but they seem to be stuck on 0.9.6.

**Comment by aleixpol** [comment]
Well we need to make a proper 0.10 version anyway. We have important changes on the pipeline here.

**Comment by ximion** [comment]
Heh, reminds me of the last time I made a release of QPK which took ages to go through Freedesktop limbo with me not having permissions on some directories... The fastest way back then was to just ask @hughsie to make a release (the FD.o admins acted almost two years later on my ticket back then :P) - and him making another release soon again would be the fastest way again, I guess.

(Or we switch download locations in the long run, but then it will be annoying to notify all distros of the change)

**Pull request merged**
